[Pal] Add missing const qualifier
    ../Pal/src/db_rtld.c: In function ‘load_elf_object_by_handle’:
    ../Pal/src/db_rtld.c:455:19: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
    455 |         errstring = "ELF file with a strange size";
        |                   ^

Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>